FROM public.ecr.aws/lambda/python:3.12
COPY requirements-aws.txt .
RUN pip install --no-cache-dir -r requirements-aws.txt --target "${LAMBDA_TASK_ROOT}"
COPY . ${LAMBDA_TASK_ROOT}
CMD ["lambda_handler.handler"]
